### PR TITLE
support for customised socket creation method

### PR DESCRIPTION
**Pull request by hans-lizihan**
@sergi , we need to use a proxy (e.g. https://www.socks-proxy.net/) to fix our server's ip address, i guess this is the minimum changes. please help to take a look, many thanks 😆

### CODE REVIEW

**Comment by sergi** [comment]
That's a good addition, thanks! Would it be possible for you to add a test and a small reference to this option in the README? Thanks.

**Comment by hans-lizihan** [comment]
@sergi updated, see if it makes sense, many thx~

**Comment by sergi** [comment]
Perfect, thanks so much for this PR :)

**Comment by hans-lizihan** [comment]
@sergi is that possible that you make a minor release for this?

**Pull request merged**
