### PR TITLE
close sockets when opened but won't be used

### PR DESCRIPTION
**Pull request by trescube**
I think that there's an issue in the library when `get`ing or `put`ing a file and an error is encountered.  The problem is that `getGetSocket` and `getPutSocket` open a socket and setup its error handling but if an error is encountered (such as a file not found 550) then the callback passes the error along but never closes the socket, so the process hangs when exiting normally due to open sockets.  The client is able to execute more `get`s but it appears that errors allow sockets to be accumulated until explicitly killed.  

There is already a test for a [file not present](https://github.com/sergi/jsftp/blob/master/test/jsftp_test.js#L654-L662) error in a `get` so I didn't modify the test suite.  I do all my testing in tape and am unfamiliar with mocha so I'm not familiar with replicating this exact scenario, but here is an example of the code failing in current master but passing in this PR:

```javascript
const {FtpSrv, FileSystem} = require('ftp-srv');
const JSFtp = require('jsftp');

const ftp_server = new FtpSrv('ftp://127.0.0.1:21000');

ftp_server.on('login', ( data , resolve, reject) => resolve() );

ftp_server.listen().then(() => {
  const ftp_client = new JSFtp({ host: '127.0.0.1', port: 21000});

  ftp_client.get('/this_file_does_not_exist.zip', (err) => {
    if (err) {
      console.error(`ERROR OCCURRED: ${err}`);
    }

    ftp_server.close().then(() => {
      console.error('closed server');
    });

  });

});
```

### CODE REVIEW

**Comment by sergi** [comment]
Thank you so much for this PR!

When you say it fails in current master, do you mean that it actually crashes or you are able to observe any problem? Or are we talking about (obviously also bad) open sockets left around filling up memory?

**Comment by trescube** [comment]
It leaves open sockets laying around and in the case of the attached node script, the process just hangs waiting to exit.  With this PR applied, the process exits normally.

**Comment by sergi** [comment]
Fantastic. I have recently made a new release and looks like your patch can’t be cleanly applied anymore. If you update it I’ll be glad to merge the patch.

**Comment by trescube** [comment]
Hey, I merged from upstream/master but the tests were unable to run to completion (couldn't get them to run on master either), but I fixed with the following: 

- added `after` suite shutdown handler to close the internal FTP server, which was causing the tests to hang
- fixed "test streaming put" test by removing init of local `ftp` instead of using one for test harness
- fixed "Test that onConnect" testis called" by calling `destroy` on local `ftp2`

All travis tests now pass.

**Comment by sergi** [comment]
Thanks @trescube for your work here. That's what OSS is all about. Cheers!

**Comment by trescube** [comment]
Thanks for making a fantastic FTP client!

**Pull request merged**
